article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name="article"
urlpatterns = [
   path('dashboard',views.dashboard,name="dashboard"),
   path('addarticle',views.addarticle,name="addarticle"),
   path('article/<int:id>',views.detail,name="detail"),
   path('update/<int:id>',views.updateArticle,name="update"),
   path('delete/<int:id>',views.deleteArticle,name="delete"),
   path('',views.articles,name="articles"),
   path('comment/<int:id>',views.addComment,name="comment"),
]

djangoBlog/urls.py
#url maplerini adreslerini verdiğimizde çalıştırılacak kodları, fonksiyonları barındırır
from django.contrib import admin
from django.urls import path,include
from article import views #oluşturduğumuz index response ı urlye katıyoruz
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),#boş bıraktıgımız zaman localhost çalışır index url sini belirtiyoruz
    path('about/', views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),#user bölümündeki url leri sonuna ekler
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name="user"
urlpatterns = [
   path('register/',views.register,name="register"),
   path('login/',views.loginUser,name="login"),
   path('logout/',views.logoutUser,name="logout")
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Python Öğreniyorum</a><!--index djangoBlog klasöründe olduğu için direkt dizin ismi verilerek ulaşılabilir-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <!--mr auto elementleri sola yaslar-->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımda</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <!--mr auto elementleri sağa yaslar-->
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:logout' %}">Çıkış yap</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}">Giriş yap</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}">Kayıt ol</a>
        </li>
        {% endif %}
        </li>
      </ul>
    </div>
  </nav>

templates/includes/postTemplate.html
<div class="container">

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <h1 class="mt-4">Post Title</h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="#">Start Bootstrap</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on January 1, 2019 at 12:00 PM</p>

            <hr>

            <!-- Preview Image -->
            <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

            <hr>

            <!-- Post Content -->
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut,
                error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae
                laborum minus inventore?</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste
                ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus,
                voluptatibus.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde
                eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis.
                Enim, iure!</p>

            <blockquote class="blockquote">
                <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
                </p>
                <footer class="blockquote-footer">Someone famous in
                    <cite title="Source Title">Source Title</cite>
                </footer>
            </blockquote>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat
                totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam
                tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae?
                Qui, necessitatibus, est!</p>
        </div>
    </div>
</div>