article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name="article"
urlpatterns = [
   path('dashboard',views.dashboard,name="dashboard"),
   path('addarticle',views.addarticle,name="addarticle"),
   path('article/<int:id>',views.detail,name="detail"),
   path('update/<int:id>',views.updateArticle,name="update"),
   path('delete/<int:id>',views.deleteArticle,name="delete"),
   path('',views.articles,name="articles"),
   path('comment/<int:id>',views.addComment,name="comment"),
]

djangoBlog/urls.py
#url maplerini adreslerini verdiğimizde çalıştırılacak kodları, fonksiyonları barındırır
from django.contrib import admin
from django.urls import path,include
from article import views #oluşturduğumuz index response ı urlye katıyoruz
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),#boş bıraktıgımız zaman localhost çalışır index url sini belirtiyoruz
    path('about/', views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),#user bölümündeki url leri sonuna ekler
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name="user"
urlpatterns = [
   path('register/',views.register,name="register"),
   path('login/',views.loginUser,name="login"),
   path('logout/',views.logoutUser,name="logout")
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
#uygulamaya özgü tablolar ve modeller class halinde burada oluşturulur
#yeni model eklendiğinde veya güncelleme yapıldığında:
#"python manage.py makemigrations" ve "python manage.py migrate" ile bunu veri tabanına kaydediyoruz
# Create your models here.
class Article(models.Model):
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlık")
    content=RichTextField()
    #content=models.TextField(verbose_name="İçerik")
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma tarihi")
    article_image=models.FileField(blank=True,null=True,verbose_name="Makeleye fotoğraf ekleyin")
    def __str__(self):
        return self.title  #admin panelinde makalelerin isimleri nasıl görüneceğini belirliyoruz
    class Meta:
        ordering = ['-created_date']#en son güncellenen veya eklenen makale en başta olacak
class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author=models.CharField(max_length=50,verbose_name="İsim")
    comment_content=models.CharField(max_length=200,verbose_name="Yorum")
    comment_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article
        fields=["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
#herhangi bir url mapine göre çalıştırılacak kod ve fonksiyonları bardındıran dosya
# Create your views here.

def index(request):
    context={
        "number1":[1,2,3,4,5,6,7]
    }
    #index çağırıldığında işlenecek fonksiyon belirtilir
    #return HttpResponse("Anasayfa")
    return render(request,"index.html",context)#otomatik templates klasörüne baktığı için düz isim
def about(request):
    return render(request,"about.html")
def detail(request,id):
    return HttpResponse("Detail:"+str(id))
@login_required(login_url='user:login')
def dashboard(request):
    articles=Article.objects.filter(author=request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url='user:login')
def addarticle(request):
    form=ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article=form.save(commit=False)#article objesi oluşturup veri tabanına kaydetmeye çalışır ama authoru kendimiz vermemiz lazım
        article.author=request.user
        article.save()
        messages.success(request,"Makale oluşturuldu.")
        return redirect("article:dashboard")
    
    return render(request,"addarticle.html",{"form":form})
def detail(request,id):
    #article=Article.objects.filter(id=id).first()#bulduğu ilk elementi döner first() demezsek liste döner tek obje dönmez
    article=get_object_or_404(Article,id=id)#eğer objeye ulaşamazsa sayfa 404 hatası verir
    comments=article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
def articles(request):
    keyword=request.GET.get("keyword")#arama çubuğu için 
    if keyword:#eğer kelime var ise
        articles=Article.objects.filter(title__contains=keyword)
        return render(request,"articles.html",{"articles":articles})
    articles=Article.objects.all()
    context={
        "articles":articles
    }
    return render(request,"articles.html",context)
@login_required(login_url='user:login')
def updateArticle(request,id):
    article=get_object_or_404(Article,id=id)
    form=ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Makale güncellendi")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})
@login_required(login_url='user:login')
def deleteArticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale başarıyla silindi")
    return redirect("article:dashboard")
def addComment(request,id):
    article=get_object_or_404(Article,id=id)

    if request.method =="POST":
        comment_author=request.POST.get("comment_author")
        comment_content=request.POST.get("comment_content")
        newComment=Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article=article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}
{% block body %}
    <p>
        <h3 style="text-align: center;">Hakkımda</h3>
        <hr>
        Herkese merhaba.Ben Muhammet ERTAŞ. TAÜ Bilgisayar Mühendisliği 2.sınıf öğrencisiyim. 
        Şu anda mevcut yazılım dillerini öğrenmekteyim. İleride başarılı bir bilgisayar mühendisi olmak, 
        güzel projeler üretmek ve teknoloji dünyasına yeni bilgiler katmak büyük bir hayalim.

        <hr>
    </p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3> <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makale ekle</button>
        </form>
    </div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}
<h3 style="text-align: center;">Makaleler</h3>
<hr>
<!--arama çubuğu oluşturuyoruz-->
<form>
    {% csrf_token %}
    <div class="search" >
        <input type="text" name="keyword" class=" input-sm" maxlength="64" placeholder="Ara...">
         <button type="submit" class="btn btn-danger btn">&nbsp Ara &nbsp</button>
        </div>
</form>
{% if articles %}
<!--
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
-->
{% for article in articles %}

<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-12">

        <!-- Title -->
        <a href="{% url 'article:detail' article.id %}"><!--/articles/article/{{article.id}} ile aynı tanım ama dinamik hali-->
            <h3 class="mt-4" style="text-align: center;">{{article.title}}</h3>
        </a>

        <!-- Author -->
        <p class="lead" style="text-align: center;">
            Yazar: {{article.author.username}}
        </p>


        <!-- Date/Time -->
        <p style="text-align: center;">Tarih: {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}


        <!-- Post Content -->
        <p>{{article.content|safe|truncatewords:30}}</p>
        <!--djangonun kendi template filtrelerini kullandık
            https://docs.djangoproject.com/en/3.1/ref/templates/builtins/-->
        <a style="float: right;" href="{% url 'article:detail' article.id %}" class="btn btn-danger">Devamını oku</a>
        <br>
        <hr>
    </div>
    <!-- /.row -->

</div>
{% endfor %}
{% else %}
<div class="alert alert-danger">Makale bulunamadı</div>
{% endif %}
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}.</small>
</p>
<a class="btn btn-danger" href="/articles/addarticle">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="/articles/update/{{article.id}}" class="btn btn-danger">Güncelle</a></td>
            <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="alert alert-danger">Henüz bir makaleniz bulunmuyor.</div>
{% endif %}
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="container">

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <h3 class="mt-4">{{article.title}}</h3>

            <!-- Author -->
            <p class="lead">
                Yazar: {{article.author.username}}
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Tarih: {{article.created_date}}</p>

            <hr>

            <!-- Preview Image -->
            {% if article.article_image %}
            <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
            {% endif %}


            <!-- Post Content -->
            <p>{{article.content|safe}}</p>
            <hr>
            <h3>Yorumlar</h3>
            <hr>
            {% if comments %}
            <!-- Single Comment -->
            {% for comment in comments %}
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{comment.comment_author}}</h5>
                    {{comment.comment_date}} <br>
                    {{comment.comment_content}}
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-danger">Henüz bir yorum yapılmamış. İlk yorum yapan siz olun.</div>
            {% endif %}
            <hr>
            <!-- Comments Form -->
            <div class="card my-4">
                <h5 class="card-header">Yorum ekle:</h5>
                <div class="card-body">
                    <form method="POST" action="{% url 'article:comment' article.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">İsim</label>
                            <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput"
                                placeholder="İsminizi girin...">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Yorum</label>
                            <textarea name="comment_content" class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-danger">Ekle</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
</div>
{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}
<div class="jumbotron text-center">
    <h3>Python Öğreniyorum Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz. </p>
</div>
<!--
{% if number1 == 10 %}
<p>Sayımız 10'a eşittir.</p>
{% else %}
<p>Sayımız 10'a eşit değildir.</p>
{% endif %}-->
<!--<ul>
{% for sayi in number1 %}
<li>{{sayi}}</li>
{% endfor %}
</ul>-->
<p>
    {% if request.user.is_authenticated %}
        Giriş yapılmış, {{request.user.username}}.
    {% else %}
        Giriş yapılmamış.
    {% endif %}
</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>DjangoBlog</title>
</head>

<body>
    {% include "includes/navbar.html" %}
    <div class="container" style="margin-top:100px; margin-bottom:50px; ">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == "info" %}
        <div class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% block body %}

        {% endblock body %}
    </div>




    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
</body>

</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}<!--Crispy formu dahil ettik daha güzel görünmesi için-->
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş yap</h3> <hr>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Giriş yap</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt ol</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            <!--bilgi çalınmasını engeller-->
            {{form|crispy}}
            <!--formu görüntülemek için .as_p diyoruz--> <br>
            <button type="submit" class="btn btn-danger">Kayıt ol</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3> <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makaleyi güncelle</button>
        </form>
    </div>
  </div>
{% endblock body %}